# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50b19198220218c589eea3793fe2ae55735008100c072b31deed2b7d14b3e5b323e6cb8ff0b2a8b2f8c66b498d64227a256d90aeabbd62838b227133adf3cba1

test:
  secret_key_base: db070c99d725854eb4673614f75e4e7f181b4eaafb6ee785a4393162fa7e1655723caff1b818497ffee803950c1c2c3ce6c0880bee51a55e6ea10b7d1a3f5e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
